[project]
name = "random-joke-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.43.2",
]

[tool.uv.workspace]
members = ["pakistani_jokes_api", "Pakistani_random_jokes"]
